export const provincesAndCities = [
  {
    city: "An Giang",
    province: "An Giang",
    provinceValue: "an-giang",
    distanceToHCMC: 232,
    distanceToHN: 1890,
  },
  {
    city: "Vũng Tàu",
    province: " Vũng Tàu",
    provinceValue: "ba-ria-vung-tau",
    distanceToHCMC: 125,
    distanceToHN: 1749,
  },
  {
    city: "Bạc Liêu",
    province: "Bạc Liêu",
    provinceValue: "bac-lieu",
    distanceToHCMC: 291,
    distanceToHN: 2063,
  },
  {
    city: "Bắc Giang",
    province: "Bắc Giang",
    provinceValue: "bac-giang",
    distanceToHCMC: 1787,
    distanceToHN: 50,
  },
  {
    city: "Bắc Kạn",
    province: "Bắc Kạn",
    provinceValue: "bac-kan",
    distanceToHCMC: 1693,
    distanceToHN: 162,
  },
  {
    city: "Bắc Ninh",
    province: "Bắc Ninh",
    provinceValue: "bac-ninh",
    distanceToHCMC: 1665,
    distanceToHN: 31,
  },
  {
    city: "Bến Tre",
    province: "Bến Tre",
    provinceValue: "ben-tre",
    distanceToHCMC: 87,
    distanceToHN: 1764,
  },
  {
    city: "Bình Định",
    province: "Bình Định",
    provinceValue: "binh-dinh",
    distanceToHCMC: 649,
    distanceToHN: 1074,
  },
  {
    city: "Bình Dương",
    province: "Bình Dương",
    provinceValue: "binh-duong",
    distanceToHCMC: 27,
    distanceToHN: 1660,
  },
  {
    city: "Bình Phước",
    province: "Bình Phước",
    provinceValue: "binh-phuoc",
    distanceToHCMC: 116,
    distanceToHN: 1785,
  },
  {
    city: "Bình Thuận",
    province: "Bình Thuận",
    provinceValue: "binh-thuan",
    distanceToHCMC: 198,
    distanceToHN: 1545,
  },
  {
    city: "Cà Mau",
    province: "Cà Mau",
    provinceValue: "ca-mau",
    distanceToHCMC: 307,
    distanceToHN: 2223,
  },
  {
    city: "Cần Thơ",
    province: "Cần Thơ",
    provinceValue: "can-tho",
    distanceToHCMC: 169,
    distanceToHN: 1892,
  },
  {
    city: "Cao Bằng",
    province: "Cao Bằng",
    provinceValue: "cao-bang",
    distanceToHCMC: 1572,
    distanceToHN: 281,
  },
  {
    city: "Đà Nẵng",
    province: "Đà Nẵng",
    provinceValue: "da-nang",
    distanceToHCMC: 767,
    distanceToHN: 767,
  },
  {
    city: "Đắk Lắk",
    province: "Đắk Lắk",
    provinceValue: "dak-lak",
    distanceToHCMC: 402,
    distanceToHN: 1327,
  },
  {
    city: "Đắk Nông",
    province: "Đắk Nông",
    provinceValue: "dak-nong",
    distanceToHCMC: 366,
    distanceToHN: 1474,
  },
  {
    city: "Điện Biên",
    province: "Điện Biên",
    provinceValue: "dien-bien",
    distanceToHCMC: 1999,
    distanceToHN: 474,
  },
  {
    city: "Đồng Nai",
    province: "Đồng Nai",
    provinceValue: "dong-nai",
    distanceToHCMC: 39,
    distanceToHN: 1662,
  },
  {
    city: "Đồng Tháp",
    province: "Đồng Tháp",
    provinceValue: "dong-thap",
    distanceToHCMC: 139,
    distanceToHN: 1881,
  },
  {
    city: "Gia Lai",
    province: "Gia Lai",
    provinceValue: "gia-lai",
    distanceToHCMC: 521,
    distanceToHN: 1080,
  },
  {
    city: "Hà Giang",
    province: "Hà Giang",
    provinceValue: "ha-giang",
    distanceToHCMC: 1970,
    distanceToHN: 320,
  },
  {
    city: "Hà Nam",
    province: "Hà Nam",
    provinceValue: "ha-nam",
    distanceToHCMC: 1613,
    distanceToHN: 63,
  },
  {
    city: "Hà Nội",
    province: "Hà Nội",
    provinceValue: "ha-noi",
    distanceToHCMC: 1680,
    distanceToHN: 0,
  },
  {
    city: "Hà Tĩnh",
    province: "Hà Tĩnh",
    provinceValue: "ha-tinh",
    distanceToHCMC: 545,
    distanceToHN: 340,
  },
  {
    city: "Hải Dương",
    province: "Hải Dương",
    provinceValue: "hai-duong",
    distanceToHCMC: 1700,
    distanceToHN: 72,
  },
  {
    city: "Hải Phòng",
    province: "Hải Phòng",
    provinceValue: "hai-phong",
    distanceToHCMC: 1680,
    distanceToHN: 120,
  },
  {
    city: "Hậu Giang",
    province: "Hậu Giang",
    provinceValue: "hau-giang",
    distanceToHCMC: 225,
    distanceToHN: 1947,
  },
  {
    city: "Hòa Bình",
    province: "Hòa Bình",
    provinceValue: "hoa-binh",
    distanceToHCMC: 1350,
    distanceToHN: 76,
  },
  {
    city: "Hưng Yên",
    province: "Hưng Yên",
    provinceValue: "hung-yen",
    distanceToHCMC: 1640,
    distanceToHN: 40,
  },
  {
    city: "Khánh Hòa",
    province: "Khánh Hòa",
    provinceValue: "khanh-hoa",
    distanceToHCMC: 448,
    distanceToHN: 1278,
  },
  {
    city: "Kiên Giang",
    province: "Kiên Giang",
    provinceValue: "kien-giang",
    distanceToHCMC: 295,
    distanceToHN: 1964,
  },
  {
    city: "Kon Tum",
    province: "Kon Tum",
    provinceValue: "kon-tum",
    distanceToHCMC: 522,
    distanceToHN: 1164,
  },
  {
    city: "Lai Châu",
    province: "Lai Châu",
    provinceValue: "lai-chau",
    distanceToHCMC: 1860,
    distanceToHN: 442,
  },
  {
    city: "Lâm Đồng",
    province: "Lâm Đồng",
    provinceValue: "lam-dong",
    distanceToHCMC: 308,
    distanceToHN: 1487,
  },
  {
    city: "Lạng Sơn",
    province: "Lạng Sơn",
    provinceValue: "lang-son",
    distanceToHCMC: 1824,
    distanceToHN: 158,
  },
  {
    city: "Lào Cai",
    province: "Lào Cai",
    provinceValue: "lao-cai",
    distanceToHCMC: 1964,
    distanceToHN: 279,
  },
  {
    city: "Long An",
    province: "Long An",
    provinceValue: "long-an",
    distanceToHCMC: 47,
    distanceToHN: 1708,
  },
  {
    city: "Nam Định",
    province: "Nam Định",
    provinceValue: "nam-dinh",
    distanceToHCMC: 1620,
    distanceToHN: 87,
  },
  {
    city: "Nghệ An",
    province: "Nghệ An",
    provinceValue: "nghe-an",
    distanceToHCMC: 1526,
    distanceToHN: 370,
  },
  {
    city: "Ninh Bình",
    province: "Ninh Bình",
    provinceValue: "ninh-binh",
    distanceToHCMC: 1583,
    distanceToHN: 95,
  },
  {
    city: "Ninh Thuận",
    province: "Ninh Thuận",
    provinceValue: "ninh-thuan",
    distanceToHCMC: 350,
    distanceToHN: 1371,
  },
  {
    city: "Phú Thọ",
    province: "Phú Thọ",
    provinceValue: "phu-tho",
    distanceToHCMC: 1750,
    distanceToHN: 80,
  },
  {
    city: "Phú Yên",
    province: "Phú Yên",
    provinceValue: "phu-yen",
    distanceToHCMC: 560,
    distanceToHN: 1094,
  },
  {
    city: "Quảng Bình",
    province: "Quảng Bình",
    provinceValue: "quang-binh",
    distanceToHCMC: 522,
    distanceToHN: 492,
  },
  {
    city: "Quảng Nam",
    province: "Quảng Nam",
    provinceValue: "quang-nam",
    distanceToHCMC: 800,
    distanceToHN: 777,
  },
  {
    city: "Quảng Ngãi",
    province: "Quảng Ngãi",
    provinceValue: "quang-ngai",
    distanceToHCMC: 682,
    distanceToHN: 832,
  },
  {
    city: "Quảng Ninh",
    province: "Quảng Ninh",
    provinceValue: "quang-ninh",
    distanceToHCMC: 1700,
    distanceToHN: 150,
  },
  {
    city: "Quảng Trị",
    province: "Quảng Trị",
    provinceValue: "quang-tri",
    distanceToHCMC: 1120,
    distanceToHN: 598,
  },
  {
    city: "Sóc Trăng",
    province: "Sóc Trăng",
    provinceValue: "soc-trang",
    distanceToHCMC: 231,
    distanceToHN: 2080,
  },
  {
    city: "Sơn La",
    province: "Sơn La",
    provinceValue: "son-la",
    distanceToHCMC: 2024,
    distanceToHN: 265,
  },
  {
    city: "Tây Ninh",
    province: "Tây Ninh",
    provinceValue: "tay-ninh",
    distanceToHCMC: 99,
    distanceToHN: 1743,
  },
  {
    city: "Thái Bình",
    province: "Thái Bình",
    provinceValue: "thai-binh",
    distanceToHCMC: 1711,
    distanceToHN: 110,
  },
  {
    city: "Thái Nguyên",
    province: "Thái Nguyên",
    provinceValue: "thai-nguyen",
    distanceToHCMC: 1782,
    distanceToHN: 75,
  },
  {
    city: "Thanh Hóa",
    province: "Thanh Hóa",
    provinceValue: "thanh-hoa",
    distanceToHCMC: 1666,
    distanceToHN: 140,
  },
  {
    city: "Thừa Thiên Huế",
    province: "Thừa Thiên Huế",
    provinceValue: "thua-thien-hue",
    distanceToHCMC: 1044,
    distanceToHN: 654,
  },
  {
    city: "Tiền Giang",
    province: "Tiền Giang",
    provinceValue: "tien-giang",
    distanceToHCMC: 70,
    distanceToHN: 1911,
  },
  {
    city: "Hồ Chí Minh",
    province: "Hồ Chí Minh",
    provinceValue: "tp-ho-chi-minh",
    distanceToHCMC: 0,
    distanceToHN: 1680,
  },
  {
    city: "Trà Vinh",
    province: "Trà Vinh",
    provinceValue: "tra-vinh",
    distanceToHCMC: 149,
    distanceToHN: 1875,
  },
  {
    city: "Tuyên Quang",
    province: "Tuyên Quang",
    provinceValue: "tuyen-quang",
    distanceToHCMC: 1744,
    distanceToHN: 140,
  },
  {
    city: "Vĩnh Long",
    province: "Vĩnh Long",
    provinceValue: "vinh-long",
    distanceToHCMC: 136,
    distanceToHN: 1930,
  },
  {
    city: "Vĩnh Phúc",
    province: "Vĩnh Phúc",
    provinceValue: "vinh-phuc",
    distanceToHCMC: 1703,
    distanceToHN: 66,
  },
  {
    city: "Yên Bái",
    province: "Yên Bái",
    provinceValue: "yen-bai",
    distanceToHCMC: 1962,
    distanceToHN: 183,
  },
].sort((a, b) => a.province.localeCompare(b.province));
